# trait used to check
## root
### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Alcantara_et_al_2018_Accelerated_diversification_and_functional_trait_e.txt
(bouckaert et al., 2014). we based topological priors (i.e. the monophyly of velloziaceae and of pandanales) on the results from the non-clock mrbayes analysis. we excluded the two most distant outgroups (acorus gramineus and encholirium scrutor), as including them in exploratory runs led to very large confidence intervals for the root age of the tree, and much longer times until mcmc convergence. there are no known fossils of velloziaceae, so for calibration purposes we used the oldest fossil known for the order pandanales, represented in our matrix by members of velloziaceae and three outgroups: cyclanthus bipartitus poit. ex a.rich. and thoracocarpus

114 108 14 2 110 (96–123) 92 (69–110) na na 2 hertweck et al. (2015) (pl) magallón et al. (2015) (ucln & pl) 116 (110–122) 103 (95–111) pl: ~90 na 1 pandanales tree-dating, focus on divergence times of velloziaceae, use of 1 fossil calibration point secondary calibration of the monocots tree-root, based on a previous calibration using 8 fossil points monocots tree-dating, focus on positioning of triuridaceae and divergence dates of pandanales, use of 4 fossil calibration points monocots tree-dating based on 11 fossil calibration points ucln: 110.5 (96.5–123) pl: 118.31 (114–121) ucln: 72.35 (53–100) pl: 103.44 (99–109) ucln: 72.35 (53–100)

of vellozia in the campos rupestres will require a deeper understanding of the origins of alternative drought resistance strategies in the family. it will also be important to consider how other ecological features, such as responses to nutrient soil availability (ayensu, 1973; oliveira et al., 2016) and altitude (mello-silva, 1995), root specializations (oliveira et al., 2015), fire resistance (conceição and orr, 2012), and interactions with pollinators and herbivores (sazima and sazima, 1990, landau et al., 1999; jacobi and sarto, 2007), might have contributed to diversification in vellozia. the ecological diversity and endemism of vellozia and other plant clades of the campos

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Aliscioni_et_al_2012_New_grass_phylogeny_resolves_deep_evolutionary_rel.txt
phylogeny for these analyses because it is far better sampled and because it contains all of the c4 taxa and suspected transitions between character states. an appropriate k value was estimated using the cross validation procedure in r8s (sanderson, 2003), and used to smooth our bayesian consensus tree with a root age set at 1. we then multiplied the branch lengths by 100 to make the computational steps more feasible. we distributed as many pacmad species as possible among the tips of our tree based on genus richness estimates from either the grass genera of the world or the tropicos taxonomic

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Anacker_et_al_2011_Origins_and_consequences_of_serpentine_endemism_in.txt
l . a nac k e r e t a l . we tested for transition rate biases on individual genera and on all genera simultaneously. first, we used bayestraits (pagel and meade 2006) to analyze each genus separately. this involved the multistate option, exponential hyperpriors, and a uniform frequency root state assumption; the last assumption can sometimes be problematic (goldberg and igic 2008), but that problem renders our test conservative and is mitigated by the presence of a third character state. second, to increase our power to estimate transition rates, we combined phylogenies for all 23 genera into a joint

they are not completely independent, they are very distantly related from one another. for instance, the 23 genera sampled represent 17 families. multiple genera were sampled in only two families (asteraceae [6] and apiaceae [2]). even in these two families, no two sampled genera are sister genera. furthermore, fixing the root of each genus to nonserpentine to account for the relatively recent emergence of serpentine, as we did for the bisse and geosse analyses described below, is a reasonable means to account for the relatively recent emergence of serpentine. transitions to serpentine affinity character states deeper than the level of genus

means to account for the relatively recent emergence of serpentine. transitions to serpentine affinity character states deeper than the level of genus in our dataset are impossible. when serpentine soils become available, at approximately the age of these genera, transitions to (and from) serpentine then proceeded independently from the nonserpentine root state in each genus, removing the shared history of the genera with regard to this character. on this set of combined trees, we used tools in the r package diversitree (fitzjohn 2010) to conduct a bayestraits-like analysis, including estimates of transition rates and model comparisons, as described above for the

qne and qet = qte . then, we test the full model against each of the three constrained models described above (i.e., qen = 0, qet = 0, and qen = qet = 0). in the analysis of the combined phylogenies, we used broad exponential priors and the conditional likelihood root state assumption, which deals naturally with the constraints of irreversible models (fitzjohn et al. 2009). diversification and transition rates to allow for character state-specific speciation and extinction rates, we performed two analyses, treating habitat occupancy as a two-state character (bisse) or a three-state character (geosse) 368 evolution february 2011 (fig.

to be estimated (table 1), but geosse has the advantage that its three possible character states contain more information than the two possibilities for bisse (fig. s1). for both the bisse and geosse analyses, we combined genera as described above to form a single, larger dataset. we also fixed the root to the nonendemic (bisse) and nontolerator (geosse) states to reflect the relatively recent appearance of serpentine soils compared to the age of these genera. analyses were performed with the r package diversitree (fitzjohn 2010). relative ages of serpentine endemics and nonendemics for each genus, we compared the terminal branch lengths

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Andriananjamanantsoa_et_al_2016_Diversification_of_angraecum_Orchidaceae_Vandeae.txt
using a relaxed molecular clock approach as implemented in beast [57]. the combined plastid matrix was used as input data in beauti. the gtr+g+i model was selected as substitution model. a relaxed lognormal molecular clock model was selected. the yule model was selected as tree prior. the age for the root of the tree was set to a normal distribution with mean 35 million years (ma) and a standard deviation of 3 (giving a 95% ci ranging from 30.07–39.93 ma). because fossil data are rare in the orchidaceae, only three fossils having been recorded so far [58], none of them close

the orchidaceae, only three fossils having been recorded so far [58], none of them close to our group, we used the age estimate of phalaenopsis [59], a member of subtribe aeridinae sister to angraecinae which occupies a phylogenetic position near the base of tribe vandeae [24,60], to calibrate the stem root. the prior distribution of the ‘ucld.mean’ parameter was set to an exponential distribution (mean = 10.0, initial value = 1.0). four separate runs were performed in beast with 50 million generations each, sampling parameters and trees every 1000 generations. trees were summarized with burnin values set to the first 25%

age estimate for angraecinae and angraecum is approximately 4 ma older than that obtained by micheneau et al. [81]; the age of two endemic species of the reunion island (a. bracteosum and a. striatum) are younger in our results, however. this can be explained by our calibration. we set the root of the tree to 35 ± 4.9 ma following gustafsson et al. [59], while micheneau et al. [81] followed ramirez et al. [82] and fixed it at 30.37 ± 3.44 ma. the main difference between the two calibrations is based on the number of fossils used in the analyses: ramirez

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Armbruster_et_al_2009_Macroevolutionary_patterns_of_defense_and_pollinat.txt
兩 18089 evolution results are reported as the mean ⫾ se seen across 100 bayesian trees regularly resampled from approximately 40,000 bayesian trees retained from the posterior distribution. branch lengths used were based on its data and were not constrained to ultrametric, following program restrictions (57). ␣ is the estimated root value, and ␤ is the directional change parameter, measuring the overall trait change against total path length from the root, in model b. because model b was not significantly better than model a under either gradual- or speciation-change assumption, these two statistical parameters probably have no biologic meaning. downloaded by

40,000 bayesian trees retained from the posterior distribution. branch lengths used were based on its data and were not constrained to ultrametric, following program restrictions (57). ␣ is the estimated root value, and ␤ is the directional change parameter, measuring the overall trait change against total path length from the root, in model b. because model b was not significantly better than model a under either gradual- or speciation-change assumption, these two statistical parameters probably have no biologic meaning. downloaded by guest on march 2, 2020 optimization in mesquite (63). mp optimization was used for multistate traits (fig. 2) and graphic

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Azani_et_al_2019_Miocene_climate_change_as_a_driving_force_for_mult.txt
on the combined nrdna its + trnk/matk + ycf1 dataset. both analyses were performed using the maximum clade credibility tree ﬁle generated in beast but excluding the outgroups. the bbm analysis was run for 5,000,000 cycles sampling every 1000 cycles under the estimated f81 + γ model with a null root distribution. the maximum number of possible ancestral areas was set to four for both analyses. signiﬁcantly incongruent (p = 0.001). however, we combined these regions due to lack of supported conﬂict (i.e., > 0.90 pp (posterior probability) and > 75% bs (bootstrap)), except for the astracantha clade (1.00 pp and

include the outgroups not previously sampled in divergence time estimations of papilionoid legumes (appendix b). two calibration points were selected based on the estimated ages derived from the previous divergence time estimations of fabaceae (lavin et al., 2005): (1) the most recent common ancestor (mrca) of the hologalegina clade (the root node) was constrained with a mean and standard deviation (stdv) of 50.6 ± 0.9 ma; (2) the robinia stem clade with an assigned minimum age constraint of 34.0 ma. the gtr + γ + i substitution model was selected for this dataset using jmodeltest 2 (darriba et al., 2012). a

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Bacon_et_al_2018_Iriarteeae_palms_tracked_the_uplift_of_Andean_Cord.txt
been present since the an exponential age prior. sabalites carolinensis (berry, 1914) is the early cretaceous (villagomez & spikings, 2013). some segments have oldest palm fossil identified to modern affinity, and we placed it as a had positive relief since the palaeocene (bayona et al., 2013), while constraint at the root of the tree. the offset value of the exponen- there are two significant pulses of exhumation at 41 and 25–22 ma tial prior was set at 85.8 ma and the mean at 1.00 to fully represent for the northern central andes (restrepo-moreno, foster, stockli, & the fossil age range (harley,

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Bardon_et_al_2013_Origin_and_evolution_of_Chrysobalanaceae_Insights.txt
phyml version 3.0.1 maximum likelihood phylogeny reconstruction program (guindon et al., 2010), as implemented in seaview4 software (gouy, guindon & gascuel, 2010). the consensus phylogram was then roughly dated using pathd8 version 1.0 (britton et al., 2007) based on four calibration points (three fossils and one temporal constraint on the root; see below). this tree then served as input for a combined analysis of divergence times and phylogenetic topology using the software beast version 1.6.1 (drummond & rambaut, 2007). the advantage of this preliminary procedure is to provide beast with a phylogenetic hypothesis not too far from the most likely region

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Beaulieu_and_Donoghue_2013_Fruit_evolution_and_diversification_in_campanulid.txt
macroevolutionary consequences of achene fruits”). for the multistate and correlated path models, akaike’s information criterion (aic; akaike 1974) was calculated from the loglikelihood to compare the fit of two models. the log-likelihood is equivalent to the probability of observing the states at the tips summed over the probability that the root is in each character evolution november 2013 3135 j. m . b e au l i e u a n d m . j. d o n o g h u e state. the first model assumed that transition rates among states are the same (i.e., equal rates model), whereas

of ancestral states assigned to all nodes that jointly maximize the likelihood given the observed tip states and parameter estimates in q. the algorithm works by first calculating the likelihood of each observed state given the transition probabilities in q, then traversing the tree from the tips down to the root computing the likelihoods of all possible character states at each node, and only retaining states that produce the highest likelihood. the algorithm then traverses the tree from root to tip assigning each internal node the optimal character state. all analyses were carried out using the cordisc and raydisc functions contained

the likelihood of each observed state given the transition probabilities in q, then traversing the tree from the tips down to the root computing the likelihoods of all possible character states at each node, and only retaining states that produce the highest likelihood. the algorithm then traverses the tree from root to tip assigning each internal node the optimal character state. all analyses were carried out using the cordisc and raydisc functions contained within the r package corhmm (beaulieu et al. 2013a). the macroevolutionary consequences of achene fruits across campanulids, more than 80% of species exhibit the indehiscent, dry, and single-seeded

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Beaulieu_and_OMeara_2016_Detecting_hidden_diversification_shifts_in_models.txt
set the probability to 1 for both state and the resulting values become the initial conditions 1a and 1b for all species exhibiting state 1—in other for the subtending branch. the overall likelihood is the words, the probability of observing a tip demonstrating product of dr,i (t) calculated at the root. we condition state 1 is 1 if the true underlying state is 1a or 1b. this likelihood by (1 — ei (t))2 , which is the probability the initial conditions for ei (0) are all set to zero (i.e., that the two descendant lineages of the root, evolving we observe

calculated at the root. we condition state 1 is 1 if the true underlying state is 1a or 1b. this likelihood by (1 — ei (t))2 , which is the probability the initial conditions for ei (0) are all set to zero (i.e., that the two descendant lineages of the root, evolving we observe the tip at the present). incomplete sampling under the same estimates of speciation and extinction can be allowed by incorporating a state-speciﬁc or even rates, survived to the present and were sampled (nee et clade-speciﬁc sampling frequency, f , and setting the al. 1994). finally, we follow

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Bouchenak_Khelladi_et_al_2014_A_revised_evolutionary_history_of_Poales_Origins.txt
fossil information is needed to select for alternative shapes of prior distributions (i.e. exponential and/or log-normal). we used the oldest unequivocal monocot fossils, characterized by minute flowers, the perianth composed of six tepals, the unicyclic androecium of three stamens and monosulcate pollen grains (gandolfo et al., 2002), to calibrate the root node of the phylogenetic tree. it provided minimum and maximum ages of 90 and 125 myr (using a uniform distribution), respectively. we calibrated the crown node of arecales following the approach of magallón et al. (2013) (i.e. log-normal distribution with mean = 84 + 10% ma and standard deviation =

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Bouchenak_Khelladi_et_al_2014_Diversification_of_C4_grasses_Poaceae_does_not_c.txt
we constrained the crown node of this clade to a minimum age of 14 myr. the fossil of cleistochloa (dugas and retallack, 1993) provided a minimum age of 14 myr (using a uniform distribution with an upper bound of 55 myr) for the crown node of panicoideae. we enforced the root node of the grasses to be less than 130 myr, which represents the age of the earliest angiosperm fossil characterized as a tricolpate pollen grain typical of eudicots (crane et al., 2004). character optimizations and diversification analyses—we used the world grass genera database (watson and dallwitz, 1992) and grassbase (clayton

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Bouchenak_Khelladi_et_al_2015_On_the_complexity_of_triggering_evolutionary_radia.txt
age from beast, based on a minimum of 10 000 post burn-in trees. we divided each study clade (i.e. ericaceae, fagales and poales) into separate partial trees for each of the radiations. these partial trees included the nodes that led up to the respective radiation (i.e. the nodes from the root of the tree towards the radiations), and those included in the radiation (fig. 1). nodes that did not play a role in the evolutionary pathway leading to the radiation (for example in sister clades of the radiating group) were excluded. the change in the probability of presence of a variable

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Bruun_Lund_et_al_2018_Rush_hour_at_the_Museum_–_Diversification_patterns.txt
ﬁgs disperse more locally and do not use the wind for dispersal (harrison and rasplus, 2006). the hemi-epiphytic life form allows for occupation of niches that most plants do not readily colonize. hemi-epiphytes are adapted to grow in the canopy layer with low water availability and high light conditions. adaptive root ﬂexibility may also explain transitioning from forest habitats to similar dry environments expressed by lithophytes in australia (harrison, 2005; harrison et al., 2003; harrison and shanahan, 2005; rønsted et al., 2008b). transitioning between life forms. the rate of which the traits tested evolve and transition into each other is an

5. conclusion overall, the diversiﬁcation rate analyses show that ﬁgs generally follow the museum model of evolution with a gradual accumulation of species over time and with very low extinction rates and no signiﬁcant evolutionary shifts. however, the trait state-dependent analyses show that monoecy, active pollination, and having a ﬂexible root habit (i.e. hemi-epiphytes) are linked with higher diversiﬁcation rates and this is further underpinned by these character states being expressed by a subclade with higher diversiﬁcation rate. these trait states are found throughout most of the phylogenetic tree suggesting that they represent key innovations or syndromes, possibly responsible for making

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Buerki_et_al_2012_Contrasting_biogeographic_and_diversification_patt.txt
boundary between the miocene and the pliocene (fig. 2). the dispersal and extinction events inferred by lagrange are reported in two time slices: from 70 ma to 16 ma, and from 16 ma to present (fig. 3; see above for explanation). note that events depicted in figure 3 exclude the root node of the family, which has been assigned south america/sub-saharan africa as ancestral area (see fig. s3). it is not possible to make further inference on this optimization without a denser sampling of closely related families and a better supported sister relationship to hyacinthaceae, so we concentrate hereafter on the

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Buerki_et_al_2013_Spatio_temporal_history_of_the_disjunct_family_Tec.txt
common ancestor (mrca) of tecophilaeaceae is assessed as widespread between south america and tropical africa, although this result has to be considered with caution because analyses were performed without outgroup taxa for technical reasons (figs 3 and 4a). the dec model estimates that a peripheral-isolate speciation took place from the root (ac) of the family to the nodes, leading to clades i and ii (fig. 3). in this context, the mrca of clade ii inherited the whole ancestral area (ac), whereas the mrca of clade i became extinct in area c and persisted only in a (figs 3 and 4). all

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Caetano_et_al_2018_Hidden_state_models_improve_state_dependent_divers.txt
are much more frequent than 0a and 1b or area-independent diversification otherwise. as a solution to this, we recommend model averaging the “effective state proportion,” which is the expected proportion of each geographic area and hidden state combination according to the equilibrium frequencies given the model parameters, tree depth, and root weights (see appendix). this provides a useful 2320 evolution november 2018 complement to examining just rate differences among observed states. in other words, even in cases where 0a > 1a > 1b > 0b, such that the average diversification rate among hidden states is more or less the same, we

use parameters estimated under a given model to determine the expected frequency under equilibrium of each geographic area and hidden state combination across a long stretch of evolutionary time. these equilibrium frequencies are often used in a variety of ways, most notably as weights in the likelihood calculation at the root (see goldberg et al. 2011). we rely on them to complement the examination of rate differences among the observed ranges. in the main text, we describe a situation in which the diversification rate of observed state 0 is more or less the same 2322 evolution november 2018 \002 d0i→0 j

value as lineage extinction, then we simply set d01i→0i = x1 and d01i→1i = x0 . we also note that when there are no hidden states, these equations reduce exactly to the equilibrium frequencies under the original geosse formulation. the initial conditions are set according to the state at the root. in our case, as a means of accounting for the uncertainty in the starting state, we rely on the likelihood that each area gave rise to the data (fitzjohn et al. 2009). once the expected number of lineages is determined after a specified t by solving the ordinary differential equation

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Cardillo_and_Pratt_2013_Evolution_of_a_hotspot_genus_Geographic_variation.txt
cook [19], for which they assumed a minimum age of 62mya. we used lognormal priors for these calibrations because this allows page 3 of 11 for uncertainty around the age estimates, while still reflecting the belief that these ages represent minimum bounds on the estimated divergence times [20]. for the root node we used a normal prior (mean = 77, sd = 1), based on the estimated divergence time between the lineages leading to banksia and hakea / grevillea in a comprehensive genus-level phylogeny of the proteaceae [7]. because this was a secondary calibration that does not represent a minimum bound,

aic and repeated tests on the same sample of 250 phylogenies as the bisse analysis. figure 4 regressions of crown age against clade size. for each of 250 banksia phylogenies sampled from the bayesian posterior distribution, a set of independent clades was identified by counting six nodes down from the root. regressions were fitted across these clades, giving 250 slope estimates. the open circles and bars represent the median and hpd of the crown age estimates for the two non-swbp banksia clades. results banksia phylogeny and ancestral region the bayesian phylogenies recovered from chloroplast data show that banksia and dryandra are

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Cássia_Silva_et_al_2019_Niche_conservatism_drives_a_global_discrepancy_in.txt
2004). in tropical present traits related to drought and fire tolerance (bacon et al., africa, fossil pollen records suggest that savannas have been present 2017), such as subterranean stems, which are related to fire avoid‐ since the early miocene, c. 23–20 ma, but they become a prominent ance, and underground root growth, even during long periods of low element of the landscape only in the late miocene, c. 6 ma, whereas or no rainfall, in addition to the lack of flammable meristematic tis‐ seasonally dry forest‐like ecosystems evolved c. 4 ma (dupont et sue (mcpherson & williams, 1998; tomlinson, 2006). the

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Chauveau_et_al_2012_Oil_producing_flowers_within_the_Iridoideae_Irida.txt
nodes closer to the tips of the tree through addition of node probabilities. m*p and m*s differ from the two previous statistical tests by having each node probability weighted by its size (chan and moore, 2002). b1 measures tree balance as opposed to imbalance; this latter statistical test excludes the root and is sensitive to changes at the tips of the tree (shao and sokal, 1990). the mp strict consensus tree, ml best-scoring tree and bayesian majority-rule consensus tree were all used for the symmetree analysis. the bisse speciation/extinction likelihood analysis implemented in mesquite 2.75 was used to calculate the likelihood

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Couvreur_et_al_2014_Global_diversification_o_f_a_tropical_plant_growth.txt
elatior) is nested within the genus validating this assumption (cuenca and asmussen-lange, 2007). in addition, these independent evolutions will be valid if our coding assumptions of calamus and frontiers in genetics | evolutionary and population genetics evolution of climbing palms of climbing palms, a shift probability is visible along its root branch in both cases, but it is not signiﬁcant when compared to other rate shifts in palms. scale bars represent the value of the branch lengths for the bf (a) and the marginal probabilities (b). daemonorops as ancestrally “climber” are also correct. indeed, both these genera have a small proportion

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Day_et_al_2016_Is_specialization_an_evolutionary_dead_end_Testin.txt
phylogenetic tests, including trait-dependent diversification models such as bisse (maddison et al., 2007; fitzjohn et al., 2009). however, we recognize that the patterns observed may be contingent on the way that specialists and generalists have been categorized. phylogenies our analyses required phylogenies with ultrametric branch lengths (where distances from the root of the tree to every tip are equal), so when this was unavail- no. of specialists ", 
" 29 7 \001ndez-mazuecos ferna et al. (2013) 33 25 38 35 26 16 15 30 20 16 hardy & otto (2014) janz et al. (2001) johnson et al. (2009) larkin et al.

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//de_Vos_et_al_2014_Heterostyly_accelerates_diversification_via_reduce.txt
than heterostyly might be important to diversification in this group. analyses using medusa identified three shifts in diversification rate (figure 2; electronic supplementary material, table s2; [3]). notably a 2.2- to 3.5-fold increase in diversification rate was detected along the same branch where heterostyly was inferred to have evolved (see root and b–c, figure 2). this shift was robust to phylogenetic uncertainty, being recovered in each of the 100 trees sampled from the posterior distribution of phylogeny estimates. topology-based analysis using symmetree [53] also recovered a diversificationrate shift along the same branch (albeit marginally significant: p ¼ 0.06; electronic supplementary material,

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Drummond_et_al_2012_Multiple_continental_radiations_and_correlates_of.txt
shrub, transverse ranges (1500 m); (f) l. formosus, spreading rhizomatous perennial, mixed deciduous/coniferous forest, coastal ranges (1200 m); (g) l. arboreus, woody perennial shrub, pacific coastal dunes at sea level; (h) l. argenteus, erect herbaceous perennial, subalpine zone, eastern sierra nevada (2400 m); (i) l. lepidus perennial with deep tap root in volcanic talus at mono craters (2300 m); (j) l. semperflorens perennial treelet, montane andean forest (2700 m); (k) lupinus sp., woody perennial shrub, páramo (3200 m); (l) l. nubigenus, acaulescent clump-forming perennial jalca grassland close to upper elevational limit for plant growth in the andes (5000 m); (m) l.

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Ebersbach_et_al_2017_Evolutionary_radiations_in_the_species_rich_mounta.txt
within a clade that contains members of sect. ciliatae subsect. hirculoideae. this clade is the largest subclade of the species-rich section ciliatae, which originated and radiated in the qtp region [31–33]. a third rate shift (shift 3) was present in some scenarios and placed in varying locations close to the root of the saxifraga phylogeny, most often on the node separating sections heterisia (a. m. johnson) small, irregulares and saxifragella (see fig. 1) from the rest of the genus. analyses with bayesrate confirmed the presence of three diversification rate shifts within saxifraga (table 1). regarding overall rate regimes, the model with

fact that the andes and the hengduan mountains share several environmental features (e.g., young age, high physiographic heterogeneity). this suggests that comparisons of alpine radiations across the globe might also need to incorporate regional dynamics (e.g., geologic and glaciation history, biogeographic connectivity). an additional rate shift was present towards the root of the phylogeny, separating sections heterisia, irregulares, saxifragella and pseudocymbalaria (group h + i + s + p) with very low net diversification rates from the rest of saxifraga. pure birth and birth-death processes were almost equally likely in this clade, so this depauperate clade may result from very low

### /home/andrew/Dropbox/projects/AJH_DiveRS/pdfs_for_ssereview/contains_angiosperms//Feldberg_et_al_2014_Epiphytic_leafy_liverworts_diversified_in_angiospe.txt
and taxonomy of the related liverwort clades whereas the assigned age intervals were based on the recent literature on the topic (supplementary 1.2.1 and 1.2.2). age intervals were integrated as age constraints with a uniform prior distribution for the minimum age of the fossil and a maximum age of the root (475 ma). the latter accounts for uncertainties of maximum clade age due to the relative sparseness of fossils older than 35 ma49,50. the maximum age of liverworts was set to 475 ma based on the age of the oldest known cryptospores51,52. final estimates were obtained using the gtr1i1g model as

